document.querySelectorAll('.podcast-console').forEach(console=>{
 const iframe=console.querySelector('iframe'),status=console.querySelector('.player-status');
 console.querySelectorAll('[data-episode]').forEach(button=>button.addEventListener('click',()=>{
  console.querySelectorAll('[data-episode]').forEach(b=>{const selected=b===button;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));b.querySelector('.episode-play').textContent=selected?'♫':'▷';});
  iframe.src=`https://open.spotify.com/embed/episode/${button.dataset.episode}?theme=0`;
  iframe.title=`Spotify-spelare: ${button.dataset.title}`;
  status.textContent=`Valt: ${button.dataset.title}. Tryck på play i spelaren för att lyssna.`;
 }));
});
const calendar=document.querySelector('#calendar-days');
if(calendar){
 const $=s=>document.querySelector(s),services={60:{name:'Universell sittning',duration:'60 minuter',price:'899 kr'},90:{name:'Universell sittning',duration:'90 minuter',price:'1 200 kr'},healing:{name:'Reconnective healing',duration:'60 minuter',price:'699 kr'}};
 const todayParts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
 const val=t=>Number(todayParts.find(p=>p.type===t).value);
 const today=new Date(val('year'),val('month')-1,val('day'));
 let month=new Date(today.getFullYear(),today.getMonth(),1),service='60',selectedDate=null,selectedTime=null,step=1;
 const format=d=>new Intl.DateTimeFormat('sv-SE',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d);
 const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 function times(d){if(d<today||d.getDay()===0||d.getDay()===6)return [];let list=service==='90'?['09:00','11:00','14:00']:service==='healing'?['10:00','13:00']:['09:00','10:30','13:00','15:00'];list=list.filter((_,i)=>(d.getDate()+i)%4!==0);if(dateKey(d)===dateKey(today)){const now=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date());list=list.filter(t=>t>now);}return list;}
 function summary(){const s=services[service];$('#summary-service').textContent=s.name;$('#summary-duration').textContent=s.duration;$('#summary-price').textContent=s.price;$('#summary-date').textContent=selectedDate?new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'long'}).format(selectedDate):'Välj en dag';$('#summary-time').textContent=selectedTime||'Välj en tid';$('#continue-booking').disabled=!(selectedDate&&selectedTime);}
 function renderTimes(){const group=$('#time-slots');group.replaceChildren();$('#time-heading').textContent=selectedDate?'Tider '+new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'long'}).format(selectedDate):'Välj en dag i kalendern';$('#slot-status').textContent=selectedDate?'Välj en exempeltid. Alla tider visas i svensk tid.':'Dina valbara tider visas här.';if(selectedDate)for(const time of times(selectedDate)){const b=document.createElement('button');b.type='button';b.className='time-slot'+(time===selectedTime?' selected':'');b.textContent=time;b.setAttribute('aria-pressed',String(time===selectedTime));b.addEventListener('click',()=>{selectedTime=time;renderTimes();summary();$('#slot-status').textContent=`Du har valt ${time}. Du kan gå vidare till dina uppgifter.`;});group.append(b);}summary();}
 function renderCalendar(){calendar.replaceChildren();$('#calendar-month').textContent=new Intl.DateTimeFormat('sv-SE',{month:'long',year:'numeric'}).format(month);const offset=(month.getDay()+6)%7;for(let i=0;i<offset;i++){const span=document.createElement('span');span.className='calendar-empty';calendar.append(span);}const last=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();for(let day=1;day<=last;day++){const d=new Date(month.getFullYear(),month.getMonth(),day),b=document.createElement('button');b.type='button';b.className='calendar-day';b.textContent=String(day);b.disabled=times(d).length===0;b.setAttribute('aria-label',format(d)+(b.disabled?', inga tider':', lediga exempeltider'));b.setAttribute('aria-pressed',String(!!selectedDate&&dateKey(d)===dateKey(selectedDate)));if(dateKey(d)===dateKey(today))b.setAttribute('aria-current','date');if(selectedDate&&dateKey(d)===dateKey(selectedDate))b.classList.add('selected');b.addEventListener('click',()=>{selectedDate=d;selectedTime=null;renderCalendar();renderTimes();});calendar.append(b);}const diff=(month.getFullYear()-today.getFullYear())*12+month.getMonth()-today.getMonth();$('#previous-month').disabled=diff<=0;$('#next-month').disabled=diff>=3;}
 function setStep(n){step=n;['one','two','three'].forEach((s,i)=>$('#booking-step-'+s).hidden=i+1!==n);document.querySelectorAll('[data-step]').forEach(el=>{el.classList.toggle('active',Number(el.dataset.step)===n);if(Number(el.dataset.step)===n)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});if(n===2){$('#booking-name').focus();}if(n===3){$('#booking-step-three').focus();}if(n===1){$('#booking-step-one').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}}
 document.querySelectorAll('[data-service]').forEach(b=>b.addEventListener('click',()=>{service=b.dataset.service;selectedTime=null;document.querySelectorAll('[data-service]').forEach(el=>{el.classList.toggle('selected',el===b);el.setAttribute('aria-pressed',String(el===b));});$('#booking-method').value='Zoom';$('#booking-method').querySelector('[value="Telefon"]').disabled=service==='healing';$('#method-note').textContent=service==='healing'?'Healing sker på distans med ett efterföljande samtal via Zoom.':'';renderCalendar();renderTimes();}));
 $('#previous-month').addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);renderCalendar();});$('#next-month').addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);renderCalendar();});
 $('#continue-booking').addEventListener('click',()=>{if(selectedDate&&selectedTime)setStep(2);});$('.back-step').addEventListener('click',()=>setStep(1));
 $('#booking-form').addEventListener('submit',e=>{e.preventDefault();if(!selectedDate||!selectedTime||!e.target.reportValidity())return;const name=$('#booking-name').value.trim();if(!name){$('#booking-name').setCustomValidity('Skriv ditt namn.');$('#booking-name').reportValidity();return;}const s=services[service];$('#confirmation-greeting').textContent=`Tack ${name}! Så här ser din demobokning ut.`;const details=$('#confirmation-details');details.replaceChildren();for(const [label,value] of [['Din stund',`${s.name} · ${s.duration}`],['Datum',format(selectedDate)],['Tid',selectedTime+' · svensk tid'],['Möte',$('#booking-method').value],['Pris',s.price],['E-post (demo)',$('#booking-email').value]]){const row=document.createElement('div');row.className='summary-line';const key=document.createElement('span'),text=document.createElement('strong');key.textContent=label;text.textContent=value;row.append(key,text);details.append(row);}setStep(3);});
 $('#booking-name').addEventListener('input',()=>$('#booking-name').setCustomValidity(''));
 $('#restart-booking').addEventListener('click',()=>{$('#booking-form').reset();selectedDate=null;selectedTime=null;$('#booking-method').value='Zoom';renderCalendar();renderTimes();setStep(1);});
 const requested=new URLSearchParams(location.search).get('tjanst');
 if(services[requested])document.querySelector(`[data-service="${requested}"]`).click();
 renderCalendar();renderTimes();
}
